package com.rdp.security.model;

import java.util.Date;

public class SecObjPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.PK_OBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String pkObjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.FK_RES_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String fkResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.FK_PAROBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String fkParobjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.OBJ_TYPE
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String objType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.ORD_IND
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private Short ordInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.VER_NO
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String verNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.MODI_BY
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private String modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_OBJ1001.MODI_TIME
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    private Date modiTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.PK_OBJ_ID
     *
     * @return the value of SEC_OBJ1001.PK_OBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getPkObjId() {
        return pkObjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.PK_OBJ_ID
     *
     * @param pkObjId the value for SEC_OBJ1001.PK_OBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setPkObjId(String pkObjId) {
        this.pkObjId = pkObjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.FK_RES_ID
     *
     * @return the value of SEC_OBJ1001.FK_RES_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getFkResId() {
        return fkResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.FK_RES_ID
     *
     * @param fkResId the value for SEC_OBJ1001.FK_RES_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setFkResId(String fkResId) {
        this.fkResId = fkResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.FK_PAROBJ_ID
     *
     * @return the value of SEC_OBJ1001.FK_PAROBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getFkParobjId() {
        return fkParobjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.FK_PAROBJ_ID
     *
     * @param fkParobjId the value for SEC_OBJ1001.FK_PAROBJ_ID
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setFkParobjId(String fkParobjId) {
        this.fkParobjId = fkParobjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.OBJ_TYPE
     *
     * @return the value of SEC_OBJ1001.OBJ_TYPE
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getObjType() {
        return objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.OBJ_TYPE
     *
     * @param objType the value for SEC_OBJ1001.OBJ_TYPE
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setObjType(String objType) {
        this.objType = objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.ORD_IND
     *
     * @return the value of SEC_OBJ1001.ORD_IND
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public Short getOrdInd() {
        return ordInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.ORD_IND
     *
     * @param ordInd the value for SEC_OBJ1001.ORD_IND
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setOrdInd(Short ordInd) {
        this.ordInd = ordInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.VER_NO
     *
     * @return the value of SEC_OBJ1001.VER_NO
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getVerNo() {
        return verNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.VER_NO
     *
     * @param verNo the value for SEC_OBJ1001.VER_NO
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setVerNo(String verNo) {
        this.verNo = verNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.MODI_BY
     *
     * @return the value of SEC_OBJ1001.MODI_BY
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public String getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.MODI_BY
     *
     * @param modiBy the value for SEC_OBJ1001.MODI_BY
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setModiBy(String modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_OBJ1001.MODI_TIME
     *
     * @return the value of SEC_OBJ1001.MODI_TIME
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_OBJ1001.MODI_TIME
     *
     * @param modiTime the value for SEC_OBJ1001.MODI_TIME
     *
     * @mbggenerated Sat May 10 15:42:16 CST 2014
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }
}